export type Language = 'zh' | 'en'

const translations: Record<string, Record<Language, string>> = {
  // CLI messages
  'fetch.initializing': { zh: '首次运行，正在初始化配置...', en: 'First run, initializing config...' },
  'fetch.fetching': { zh: '正在采集 {n} 个信息源...', en: 'Fetching from {n} sources...' },
  'fetch.cancelled': { zh: '已取消。', en: 'Cancelled.' },
  'fetch.noSources': { zh: '所有信息源均已禁用或未定义。', en: 'All sources are disabled or undefined.' },
  'fetch.unknownSource': { zh: '⚠ 未知信息源 ID: {ids}', en: '⚠ Unknown source ID(s): {ids}' },
  'fetch.noMatch': { zh: '未找到匹配的信息源。', en: 'No matching sources found.' },
  'fetch.availableCategories': { zh: '可用板块:', en: 'Available categories:' },
  'fetch.cacheBypass': { zh: '⚠ 时间窗口扩大到 {h}h，自动跳过缓存以获取完整数据', en: '⚠ Time window extended to {h}h, bypassing cache for complete data' },
  'fetch.htmlGenerated': { zh: '✅ HTML 报告已生成: {path}', en: '✅ HTML report generated: {path}' },
  'fetch.openingBrowser': { zh: '正在打开浏览器...', en: 'Opening browser...' },
  'fetch.openHint': { zh: '提示: 添加 --open 可自动打开浏览器', en: 'Tip: add --open to open browser automatically' },
  'fetch.stats': { zh: '📊 信息源: {total} | 成功: {success} | 条目: {items}', en: '📊 Sources: {total} | Success: {success} | Items: {items}' },

  // Sources list
  'sources.list.header': { zh: '  信息源列表', en: '  Source List' },
  'sources.list.search': { zh: '  信息源列表（搜索: {q}）', en: '  Source List (search: {q})' },
  'sources.list.disabled': { zh: '  信息源列表（未开启）', en: '  Source List (disabled)' },
  'sources.list.enabled': { zh: '  信息源列表（已开启）', en: '  Source List (enabled)' },
  'sources.list.col.id': { zh: 'ID', en: 'ID' },
  'sources.list.col.name': { zh: '名称', en: 'Name' },
  'sources.list.col.adapter': { zh: '适配器', en: 'Adapter' },
  'sources.list.col.category': { zh: '板块', en: 'Category' },
  'sources.list.col.status': { zh: '状态', en: 'Status' },
  'sources.status.default': { zh: '✓ 默认', en: '✓ Default' },
  'sources.status.enabled': { zh: '✓ 已开启', en: '✓ Enabled' },
  'sources.status.disabled': { zh: '✗ 关闭', en: '✗ Disabled' },
  'sources.list.total': { zh: '  共 {total} 个信息源，{enabled} 个已启用', en: '  Total {total} sources, {enabled} enabled' },
  'sources.list.showing': { zh: '  显示 {shown} 个，共 {total} 个', en: '  Showing {shown} of {total}' },

  // Bundles
  'bundles.list.header': { zh: '  可用主题包', en: '  Available Bundles' },
  'bundles.list.hint': { zh: '  运行: reado fetch --bundle <id>  使用主题包采集', en: '  Run: reado fetch --bundle <id>  to fetch by bundle' },

  // HTML templates
  'html.generatedBy': { zh: '由 reado 生成', en: 'Generated by reado' },
  'html.stats.sources': { zh: '信息源', en: 'Sources' },
  'html.stats.success': { zh: '成功', en: 'Success' },
  'html.stats.failed': { zh: '失败', en: 'Failed' },
  'html.stats.items': { zh: '条目', en: 'Items' },
  'html.stats.cached': { zh: '缓存', en: 'Cached' },
}

let _currentLang: Language = 'zh'

export function setLanguage(lang: Language): void {
  _currentLang = lang
}

export function getLanguage(): Language {
  return _currentLang
}

export function t(key: string, vars?: Record<string, string | number>): string {
  const entry = translations[key]
  if (!entry) return key

  let str = entry[_currentLang] ?? entry['zh'] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(`{${k}}`, String(v))
    }
  }
  return str
}
